### ISSUE TITLE
How to get the whole list on onUpdate?

### ISSUE THREAD

**Issue by shyamal890** [SortableJS/ngx-sortablejs#143] opened 2019-01-10 14:20 UTC
Is there a way to obtain the whole list (`to` list) when `onUpdate` is called?

**NOTE:** There would be multiple lists and these lists would be a part of `*ngFor`.

**Comment by smnbbrv** [comment] 2019-01-14 19:39
hey guys,

could you explain more on what is the problem? I don't really get what is the intention.

Could you create a stackblitz which reproduces the problem and intention?

**Comment by mr-moon** [comment] 2019-01-15 08:48
@smnbbrv when you pass a handler to an `onUpdate` hook via:
```
this.times = [1, 2, 3, 4];
this.sortableOptions = <SortablejsOptions>{
    onUpdate: (event) => {
        ...
    }
};
```

The `this.item`s not reachable from `onUpdate` handler function, neither is HttpClient. basically that handler is run out of component scope, thus making it hard to actually update order by sending appropriate request to the backend.

**Comment by smnbbrv** [comment] 2019-01-15 15:04
Weird. I thought I used it in many places like you say and it worked.

```ts
this.sortableOptions = <SortablejsOptions>{
    onUpdate: (event) => {
        ...
    }
};
```

The `onUpdate` would have the same `this` which is accepting `this.sortableOptions` because of the arrow function.

I can believe that the below example won't work

```ts
this.sortableOptions = <SortablejsOptions>{
    onUpdate(event) {
        ...
    }
};
```

That's actually why I ask for a stackblitz reproduction.

**Comment by mr-moon** [comment] 2019-01-18 17:43
@smnbbrv sorry, bit busy, will post it early next week.

**Comment by smnbbrv** [comment] 2019-06-07 10:20
No information given => closing :(

**Closed by smnbbrv** 2019-06-07 10:20 UTC
